version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pulse_db
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: pulse_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pulse_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/pulse_ecommerce
    depends_on:
      - db

volumes:
  pgdata: